### ISSUE TITLE
AdvancedListView is very slow compared to ordinary ListView

### ISSUE THREAD

**Issue by BelikovSergey** [imagin-tech/Imagin.NET#3]
Hi!

We are using list with about 100 items (with quite complex layout) and it loads several times slower than ordinary ListView. Virtualization is enabled in style. What could be the problem?

**Comment by BelikovSergey** [comment]
I have checked, virtualization is broken (I track creation of ListViewItem inner controls) and in AdvancedListView they are all created.
This is a list of messages and we use this, to load items bottom-up. Maybe this is broken somehow by AdvancedListView.
                    <GroupStyle.Panel>
                        <ItemsPanelTemplate>
                            <VirtualizingStackPanel VerticalAlignment="Bottom"/>
                        </ItemsPanelTemplate>
                    </GroupStyle.Panel>

**Comment by BelikovSergey** [comment]
It seems that this part is broken
```
                        <Grid 
                            x:Name="PART_Grid"
                            Background="Transparent" 
                            ClipToBounds="True">
                            <ItemsPresenter Margin="{TemplateBinding Padding}"/>
                            <local:DragSelection x:Name="PART_DragSelection" Selection="{TemplateBinding DragSelection}"/>
                        </Grid>
```
It seems that it create items to recalculate grid size. If I remove grid and DragSelection - it works, but I loze dragselection (which is why I am using this listview).

**Comment by imagin-tech** [comment]
@BelikovSergey I imagine that would have something to do with the ScrollViewer as it is rather finicky when it comes to restructuring a template.

One alternative to consider is implementing drag selection using an adorner, which would likely significantly improve speed; unfortunately, I am not very experienced with adorners and have never attempted to experiment with them in this context.

I will examine the control further and see what I can come up with.

**Comment by BelikovSergey** [comment]
Thanks! I have tried to play with the template and have moved DragSelection into the ScrollViewer template and was able get it in SetScrollContentPresenter as presenter from the same template. Virtualization works, but I stuck at binding Selection to the DragSelection property.

**Comment by imagin-tech** [comment]
Placing the DragSelection control in the ScrollViewer template should work fine, but you'd have to find a way to pass the selection value from the ListBox to it. DragSelector class currently adds the DragSelection control programmatically to the grid. You'd want to add it to the ScrollViewer instead or place it in the ScrollViewer template directly. 

I recommend adding it via DragSelector because not every ScrollViewer will need it, just the ones in any ItemsControl that makes use of drag selection. You can do so two ways:

1. Access the visual tree of the ScrollViewer template and insert it (kind of complicated, but ideal).
2. Insert the control into the ScrollViewer template directly. To bind to the current selection, you can use the syntax, `Binding="{Binding (Extensions:ItemsControlExtensions.DragSelector).Selection.X, RelativeSource={RelativeSource TemplatedParent}}"`, etc. I have not tested this syntax so unfortunately you're on your own with that (for now, anyway).

Note, I did not open an issue for this, but I recently found out you cannot technically bind to a RenderTransform (in this case, we were binding the selection to a TranslateTransform); now, the TranslateTransform is updated programmatically when the position alone changes. The size still binds to DragSelection like normal. 

Also note, DragSelectionManager class has been renamed to DragSelector.

The latest version reflects these changes.

**Comment by imagin-tech** [comment]
AdvancedListView is now deprecated. I have abandoned it! I am not really interested in extending the ListView beyond basic operations so I just use ListView in the places it's needed. This applies to the latest release 5.0.
