### ISSUE TITLE
How to use PropertyGrid

### ISSUE THREAD

**Issue by brambossche** [imagin-tech/Imagin.NET#97]
Hi, 

I could make the demo run.
But out of the demo I don't find how to easily the propertygrid. 
In the  [codeproject link](https://www.codeproject.com/Articles/1092748/WPF-PropertyGrid#_comments) it is mentioned to simply select the property grid in Xaml code and use selectObject.
`<local:PropertyGrid SelectedObject="{Binding YourObject}"/>`

Problem 1: Adding propertyGrid in the Xaml code already complains on null exception.

problem2: SelectedObject is no longer a property of the control. So, how to assign the object ? 

Kind regards

**Comment by imagin-tech** [comment]
`SelectedObject` is now `Source`. So if you have an instance of the `PropertyGrid`: `myPropertyGrid.Source = mySourceObject;`

As for your first problem, I believe that has to do with the equality check in `Proportions` (which itself utilizes a faulty extension), which I fixed in the new version. Is this still not working? I was able to get it to work on my end just fine after the corrections. Please let me know so I can close this issue.

The CodeProject article is quite out of date. It will confuse more than help because so much has changed since it was last modified. If you have any other questions, feel free to open additional issues :)

**Comment by thrmotta** [comment]
Have you ever managed to release 4.5.2?

**Comment by imagin-tech** [comment]
I just released 5.0. Many of the issues plaguing the earlier version of PropertyGrid are solved including this one.
